#=================================================
# Lisence: MIT
# Author: Texot
#=================================================

name: Build Openwrt Buildenv

on:
  repository_dispatch:
  workflow_dispatch:
  deployment:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master

    - name: Enable experimental features
      run: |
        echo '{
          "experimental": true
        }' | sudo tee /etc/docker/daemon.json
        sudo service docker restart

    - name: Disk Free Spaces
      run: |
        sudo sed -i "/ExecStart/d" /usr/lib/systemd/system/docker.service
        sudo sed -i "/ExecReload/i ExecStart=/usr/bin/dockerd -H fd:// --containerd /var/run/containerd/containerd.sock --storage-opt size=20G" /usr/lib/systemd/system/docker.service
        sudo cat /usr/lib/systemd/system/docker.service
        sudo systemctl daemon-reload
        sudo service docker restart

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        DOCKER_BUILDKIT: 1
      with:
        name: jlzsss/openwrt-buildenv
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
