#=================================================
# Lisence: MIT
# Author: Texot
#=================================================

name: Build Openwrt Buildenv

on:
  repository_dispatch:
  workflow_dispatch:
  deployment:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master

    - name: Enable experimental features
      run: |
        echo '{
          "experimental": true
        }' | sudo tee /etc/docker/daemon.json
        sudo service docker restart

    - name: Disk Free Spaces
      run: |
        echo '{
          ExecStart=/usr/bin/dockerd --graph=/work/docker_data 
          --storage-driver devicemapper 
          --storage-opt dm.loopdatasize=200G 
          --storage-opt dm.loopmetadatasize=50G 
          --storage-opt dm.fs=ext4 
          --storage-opt dm.basesize=100G 
          -H fd:// --containerd /var/run/containerd/containerd.sock
        }' | sudo tee /usr/lib/systemd/system/docker.service
        sudo systemctl daemon-reload
        sudo service docker restart

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        DOCKER_BUILDKIT: 1
      with:
        name: jlzsss/openwrt-buildenv
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
