#=================================================
# Lisence: MIT
# Author: Texot
#=================================================

name: Build Openwrt Buildenv

on:
  repository_dispatch:
  workflow_dispatch:
  deployment:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master

    - name: Enable experimental features
      run: |
        echo '{
          "experimental": true
        }' | sudo tee /etc/docker/daemon.json
        sudo service docker restart

    - name: Disk Free Spaces
      run: |
       sudo cat /usr/lib/systemd/system/docker.service
       # echo '{
       #   ExecStart=/usr/bin/dockerd  -H fd:// --containerd=/run/containerd/containerd.sock -s=devicemapper --storage-opt dm.basesize=80G --storage-opt dm.loopmetadatasize=40G
       # }' | sudo tee /usr/lib/systemd/system/docker.service
       # sudo systemctl daemon-reload
       sudo systemctl status docker.service
       sudo service docker restart

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        DOCKER_BUILDKIT: 1
      with:
        name: jlzsss/openwrt-buildenv
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
