#=================================================
# Lisence: MIT
# Author: Texot
#=================================================

name: Build Openwrt Buildenv

on:
  repository_dispatch:
  workflow_dispatch:
  deployment:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master

    - name: Enable experimental features
      run: |
        echo '{
          "experimental": true
        }' | sudo tee /etc/docker/daemon.json
        sudo service docker restart

    - name: Disk Free Spaces
      run: |
        sudo sed '/ExecStart=/usr/bin/dockerd/d' /usr/lib/systemd/system/docker.service
        echo 'ExecStart=/usr/bin/dockerd  -H fd:// --containerd=/var/run/containerd/containerd.sock --storage-opt dm.basesize=100G --storage-opt dm.loopdatasize=200G --storage-opt dm.loopmetadatasize=60G --storage-opt dm.fs=ext4' | sudo tee -a /usr/lib/systemd/system/docker.service
        sudo systemctl daemon-reload
        sudo service docker restart

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        DOCKER_BUILDKIT: 1
      with:
        name: jlzsss/openwrt-buildenv
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
